package datensammer.datensammler;

public enum LocationMessung {

    GPS_LOCATION_PROVIDER,
    NETZWERK_LOCATION_PROVIDER,
    FUSED_LOCATION_PROVIDER_HIGH_ACCUANCY,
    FUSED_LOCATION_PROVIDER_BALANCED_POWER,
    FUSED_LOCATION_PROVIDER_LOW_POWER,
    FUSED_LOCATION_PROVIDER_NO_POWER
}
